# Generated by Django 4.2.3 on 2023-07-27 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_profile_name_alter_profile_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
