# Generated by Django 4.2.3 on 2023-07-30 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_conversation_question_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='question_user',
        ),
    ]
